server:
  port: 9080
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
    name: microservice-provider-user
eureka:
  client:
    service-url:
      defaultZone: http://peer1:9051/eureka/
  instance:
    prefer-ip-address: true
